config/routes.rb
Rails.application.routes.draw do

  get 'events/createevent'
  get 'pages/events'

  resources :userxes
  get 'pages/AboutMe'

  devise_for :users
  get 'pages/info'
  get 'events/createevent'

  root :to => redirect('/ideas')

  resources :ideas

end

app/models/idea.rb
class Idea < ActiveRecord::Base
  mount_uploader :picture, PictureUploader
end

app/models/testimonial.rb
class Testimonial < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/userx.rb
class Userx < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # before_action :authenticate_user!
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  layout "Aboutstatic"
    #...
  def createevent
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: [:show, :edit, :update, :destroy]

  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = Idea.all
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
  end

  # GET /ideas/new
  def new
    @idea = Idea.new
  end

  # GET /ideas/1/edit
  def edit
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(idea_params)

    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @idea }
      else
        format.html { render :new }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideas/1
  # PATCH/PUT /ideas/1.json
  def update
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to @idea, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @idea }
      else
        format.html { render :edit }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to ideas_url, notice: 'Event was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = Idea.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idea_params
      params.require(:idea).permit(:name, :description, :picture)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  layout "Aboutstatic"
    #...
end

app/controllers/testimonials_controller.rb
class TestimonialsController < ApplicationController
  before_action :set_testimonial, only: [:show, :edit, :update, :destroy]

  # GET /testimonials
  # GET /testimonials.json
  def index
    @testimonials = Testimonial.all
  end

  # GET /testimonials/1
  # GET /testimonials/1.json
  def show
  end

  # GET /testimonials/new
  def new
    @testimonial = Testimonial.new
  end

  # GET /testimonials/1/edit
  def edit
  end

  # POST /testimonials
  # POST /testimonials.json
  def create
    @testimonial = Testimonial.new(testimonial_params)

    respond_to do |format|
      if @testimonial.save
        format.html { redirect_to @testimonial, notice: 'Testimonial was successfully created.' }
        format.json { render :show, status: :created, location: @testimonial }
      else
        format.html { render :new }
        format.json { render json: @testimonial.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /testimonials/1
  # PATCH/PUT /testimonials/1.json
  def update
    respond_to do |format|
      if @testimonial.update(testimonial_params)
        format.html { redirect_to @testimonial, notice: 'Testimonial was successfully updated.' }
        format.json { render :show, status: :ok, location: @testimonial }
      else
        format.html { render :edit }
        format.json { render json: @testimonial.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /testimonials/1
  # DELETE /testimonials/1.json
  def destroy
    @testimonial.destroy
    respond_to do |format|
      format.html { redirect_to testimonials_url, notice: 'Testimonial was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_testimonial
      @testimonial = Testimonial.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def testimonial_params
      params.require(:testimonial).permit(:name, :comment, :address)
    end
end

app/controllers/userxes_controller.rb
class UserxesController < ApplicationController
  before_action :set_userx, only: [:show, :edit, :update, :destroy]

  # GET /userxes
  # GET /userxes.json
  def index
    @userxes = Userx.all
  end

  # GET /userxes/1
  # GET /userxes/1.json
  def show
  end

  # GET /userxes/new
  def new
    @userx = Userx.new
  end

  # GET /userxes/1/edit
  def edit
  end

  # POST /userxes
  # POST /userxes.json
  def create
    @userx = Userx.new(userx_params)

    respond_to do |format|
      if @userx.save
        format.html { redirect_to @userx, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @userx }
      else
        format.html { render :new }
        format.json { render json: @userx.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /userxes/1
  # PATCH/PUT /userxes/1.json
  def update
    respond_to do |format|
      if @userx.update(userx_params)
        format.html { redirect_to @userx, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @userx }
      else
        format.html { render :edit }
        format.json { render json: @userx.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /userxes/1
  # DELETE /userxes/1.json
  def destroy
    @userx.destroy
    respond_to do |format|
      format.html { redirect_to userxes_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_userx
      @userx = Userx.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def userx_params
      params[:userx]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/testimonials_helper.rb
module TestimonialsHelper
end

app/helpers/userxes_helper.rb
module UserxesHelper
end

app/views/events/createevent.html.erb
<h1>Events#createevent</h1>
<p>Find me in app/views/events/createevent.html.erb</p>

app/views/ideas/_form.html.erb
<%= form_for(@idea) do |f| %>
  <% if @idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% @idea.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ideas/edit.html.erb
<h1>Editing Picture</h1>

<%= render 'form' %>

<%= link_to 'Show', @idea %> |
<%= link_to 'Back', ideas_path %>

app/views/ideas/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <h1>Create Photo Album</h1>
  <table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ideas.each do |idea| %>
      <tr>
        <td><%= idea.name %></td>
        <td><%= idea.description %></td>
        <td><%= idea.picture %></td>
        <td><%= link_to 'Show', idea %></td>
        <td><%= link_to 'Edit', edit_idea_path(idea) %></td>
        <td><%= link_to 'Destroy', idea, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<ul class="nav navbar-nav">
  <li class="active"><%= link_to 'New Photo', new_idea_path %></li>
  <li class="active"><a href="/ideas">Link 2</a></li>
  </ul>
</div>

<br>

app/views/ideas/new.html.erb
<div class="container">
<h1>New Picture</h1>

<%= render 'form' %>

<%= link_to 'Back', ideas_path %>
</div>

app/views/ideas/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-9">
    <%= image_tag(@idea.picture_url, width: '100%') if @idea.picture.present? %>
  </div>

  <div class="col-md-3">
    <p><b>Name: </b><%= @idea.name %></p>
    <p><b>Description: </b><%= @idea.description %></p>
    <p>
      <%= link_to 'Edit', edit_idea_path(@idea) %> |
      <%= link_to 'Destroy', @idea, data: { confirm: 'Are you sure?' }, method: :delete %> |
      <%= link_to 'Back', ideas_path %>
    </p>
  </div>
</div>

app/views/pages/About.html.erb
  <h1>Pages#info</h1>
  <p>Find me in app/views/pages/AboutMe.html.erb</p>

app/views/pages/AboutMe.html.erb
  <h1>Pages#info</h1>
  <% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
  <% end %>
<%= yield %>

  <p>Find me in app/views/pages/AboutMe.html.erb</p>

app/views/pages/events.html.erb
<h1>Pages#events</h1>
<p>Find me in app/views/pages/events.html.erb</p>

app/views/pages/info.html.erb
<h1>Pages#info</h1>
<p>Find me in app/views/pages/info.html.erb</p>

app/views/testimonials/_form.html.erb
<%= form_for(@testimonial) do |f| %>
  <% if @testimonial.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@testimonial.errors.count, "error") %> prohibited this testimonial from being saved:</h2>

      <ul>
      <% @testimonial.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/testimonials/edit.html.erb
<h1>Editing Testimonial</h1>

<%= render 'form' %>

<%= link_to 'Show', @testimonial %> |
<%= link_to 'Back', testimonials_path %>

app/views/testimonials/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Testimonials</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Comment</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @testimonials.each do |testimonial| %>
      <tr>
        <td><%= testimonial.name %></td>
        <td><%= testimonial.comment %></td>
        <td><%= testimonial.address %></td>
        <td><%= link_to 'Show', testimonial %></td>
        <td><%= link_to 'Edit', edit_testimonial_path(testimonial) %></td>
        <td><%= link_to 'Destroy', testimonial, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Testimonial', new_testimonial_path %>

app/views/testimonials/new.html.erb
<h1>New Testimonial</h1>

<%= render 'form' %>

<%= link_to 'Back', testimonials_path %>

app/views/testimonials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @testimonial.name %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @testimonial.comment %>
</p>

<p>
  <strong>Address:</strong>
  <%= @testimonial.address %>
</p>

<%= link_to 'Edit', edit_testimonial_path(@testimonial) %> |
<%= link_to 'Back', testimonials_path %>

app/views/userxes/_form.html.erb
<%= form_for(@userx) do |f| %>
  <% if @userx.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@userx.errors.count, "error") %> prohibited this userx from being saved:</h2>

      <ul>
      <% @userx.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/userxes/edit.html.erb
<h1>Editing Userx</h1>

<%= render 'form' %>

<%= link_to 'Show', @userx %> |
<%= link_to 'Back', userxes_path %>

app/views/userxes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Userxes</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @userxes.each do |userx| %>
      <tr>
        <td><%= link_to 'Show', userx %></td>
        <td><%= link_to 'Edit', edit_userx_path(userx) %></td>
        <td><%= link_to 'Destroy', userx, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Userx', new_userx_path %>

app/views/userxes/new.html.erb
<h1>New Userx</h1>

<%= render 'form' %>

<%= link_to 'Back', userxes_path %>

app/views/userxes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_userx_path(@userx) %> |
<%= link_to 'Back', userxes_path %>